/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallasvistaemprendedor;

import com.mycompany.motoamigocontrol.ControladorPrincipal;
import util.Icon;

/**
 *
 * @author xiomi
 */
public class PanelRepartidorAsignado extends javax.swing.JFrame {
    
    private ControladorPrincipal controlador;

    /**
     * Creates new form PanelRepartidorAsignado
     */
    public PanelRepartidorAsignado(ControladorPrincipal controlador) {
        initComponents();
        this.controlador = controlador;
        labelHomeIcon.setIcon(Icon.cargarIcono("/imagenes/home.png", 20, 20));
        labelHistorialIcon.setIcon(Icon.cargarIcono("/imagenes/pedidos.png", 20, 20));
        labelPerfilIcon.setIcon(Icon.cargarIcono("/imagenes/perfil.png", 20, 20));
        labelIconCarrito.setIcon(Icon.cargarIcono("/imagenes/carrito.png", 25, 25));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPadre = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        tituloMotoAmigo = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        labelHomeIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelHistorialIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelPerfilIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelInfoRepartidor = new javax.swing.JPanel();
        labelIconCarrito = new javax.swing.JLabel();
        labelNombreRepartidor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelTiempoEstimado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelTiempoEstimado1 = new javax.swing.JLabel();
        panelVehiculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lavelVehiculo = new javax.swing.JLabel();
        btn_ver_seguimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPadre.setBackground(new java.awt.Color(248, 250, 252));

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 80));

        tituloMotoAmigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloMotoAmigo.setForeground(new java.awt.Color(251, 86, 0));
        tituloMotoAmigo.setText("MotoAmigo");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloMotoAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloMotoAmigo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        footerPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelHomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHomeIcon.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicio");

        labelHistorialIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHistorialIcon.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pedidos");

        labelPerfilIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPerfilIcon.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Perfil");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(footerPanelLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelHomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(78, 78, 78)
                    .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelHistorialIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                    .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelPerfilIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(56, 56, 56)))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
            .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(footerPanelLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(footerPanelLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(footerPanelLayout.createSequentialGroup()
                                    .addComponent(labelHomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel4))
                                .addGroup(footerPanelLayout.createSequentialGroup()
                                    .addComponent(labelHistorialIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel5))))
                        .addGroup(footerPanelLayout.createSequentialGroup()
                            .addComponent(labelPerfilIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelInfoRepartidor.setBackground(new java.awt.Color(255, 255, 255));

        labelIconCarrito.setBackground(new java.awt.Color(255, 204, 153));

        labelNombreRepartidor.setBackground(new java.awt.Color(204, 204, 204));
        labelNombreRepartidor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNombreRepartidor.setText("NombreDelRepartidor");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Repartidor asignado exitosamente");

        panelTiempoEstimado.setBackground(new java.awt.Color(248, 250, 252));
        panelTiempoEstimado.setPreferredSize(new java.awt.Dimension(120, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("TIEMPO ESTIMADO");

        javax.swing.GroupLayout panelTiempoEstimadoLayout = new javax.swing.GroupLayout(panelTiempoEstimado);
        panelTiempoEstimado.setLayout(panelTiempoEstimadoLayout);
        panelTiempoEstimadoLayout.setHorizontalGroup(
            panelTiempoEstimadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTiempoEstimadoLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(labelTiempoEstimado1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelTiempoEstimadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTiempoEstimadoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
        );
        panelTiempoEstimadoLayout.setVerticalGroup(
            panelTiempoEstimadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTiempoEstimadoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelTiempoEstimado1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelTiempoEstimadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTiempoEstimadoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        panelVehiculo.setBackground(new java.awt.Color(248, 250, 252));
        panelVehiculo.setPreferredSize(new java.awt.Dimension(120, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("VEHÍCULO");

        javax.swing.GroupLayout panelVehiculoLayout = new javax.swing.GroupLayout(panelVehiculo);
        panelVehiculo.setLayout(panelVehiculoLayout);
        panelVehiculoLayout.setHorizontalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(panelVehiculoLayout.createSequentialGroup()
                        .addComponent(lavelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        panelVehiculoLayout.setVerticalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lavelVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout panelInfoRepartidorLayout = new javax.swing.GroupLayout(panelInfoRepartidor);
        panelInfoRepartidor.setLayout(panelInfoRepartidorLayout);
        panelInfoRepartidorLayout.setHorizontalGroup(
            panelInfoRepartidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoRepartidorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelInfoRepartidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoRepartidorLayout.createSequentialGroup()
                        .addGroup(panelInfoRepartidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelIconCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombreRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInfoRepartidorLayout.createSequentialGroup()
                        .addComponent(panelTiempoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        panelInfoRepartidorLayout.setVerticalGroup(
            panelInfoRepartidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoRepartidorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelInfoRepartidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoRepartidorLayout.createSequentialGroup()
                        .addComponent(labelIconCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNombreRepartidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(panelTiempoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btn_ver_seguimiento.setBackground(new java.awt.Color(0, 0, 0));
        btn_ver_seguimiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ver_seguimiento.setForeground(new java.awt.Color(255, 255, 255));
        btn_ver_seguimiento.setText("Ver seguimiento");
        btn_ver_seguimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_seguimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPadreLayout = new javax.swing.GroupLayout(panelPadre);
        panelPadre.setLayout(panelPadreLayout);
        panelPadreLayout.setHorizontalGroup(
            panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPadreLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInfoRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ver_seguimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPadreLayout.setVerticalGroup(
            panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPadreLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInfoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_ver_seguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ver_seguimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_seguimientoActionPerformed
        // TODO add your handling code here:
        PanelSeguimientoPedido panelSeguimiento = new PanelSeguimientoPedido(this.controlador);
        panelSeguimiento.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ver_seguimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ver_seguimiento;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelHistorialIcon;
    private javax.swing.JLabel labelHomeIcon;
    private javax.swing.JLabel labelIconCarrito;
    private javax.swing.JLabel labelNombreRepartidor;
    private javax.swing.JLabel labelPerfilIcon;
    private javax.swing.JLabel labelTiempoEstimado1;
    private javax.swing.JLabel lavelVehiculo;
    private javax.swing.JPanel panelInfoRepartidor;
    private javax.swing.JPanel panelPadre;
    private javax.swing.JPanel panelTiempoEstimado;
    private javax.swing.JPanel panelVehiculo;
    private javax.swing.JLabel tituloMotoAmigo;
    // End of variables declaration//GEN-END:variables
}
