/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallasvistaemprendedor;

import com.mycompany.motoamigodto.pedido.PedidoDTO;
import controlador.ControladorPrincipal;
import javax.swing.ButtonGroup;
import pantallasvistarepartidor.PanelRepartidor;

/**
 *
 * @author xiomi
 */
public class PanelSolicitarEntrega extends javax.swing.JFrame {

    private ControladorPrincipal controlador;

    /**
     * Creates new form PanelSolicitarEntrega
     *
     * @param controlador
     */
    public PanelSolicitarEntrega(ControladorPrincipal controlador) {
        initComponents();
        this.controlador = controlador;
        this.setLocationRelativeTo(null);
        
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(radioCaja);
        grupo.add(radioSobre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        tituloMotoAmigo = new javax.swing.JLabel();
        principalPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        entrega = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        recoleccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        decrp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        btn_solicitarPedido_ = new util.guis.BotonNegro();
        radioCaja = new javax.swing.JRadioButton();
        radioSobre = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solicitar Pedido");

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 80));

        tituloMotoAmigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloMotoAmigo.setForeground(new java.awt.Color(251, 86, 0));
        tituloMotoAmigo.setText("MotoAmigo");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloMotoAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloMotoAmigo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        principalPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("PUNTO DE RECOLECCIÓN");

        entrega.setColumns(10);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PUNTO DE ENTREGA");

        recoleccion.setColumns(10);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("PESO APROXIMADO");

        decrp.setColumns(10);

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("DESCRIPCIÓN");

        peso.setColumns(10);

        btn_solicitarPedido_.setText("Publicar Pedido");
        btn_solicitarPedido_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitarPedido_ActionPerformed(evt);
            }
        });

        radioCaja.setText("Caja");

        radioSobre.setText("Sobre");

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(decrp, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(principalPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recoleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(principalPanelLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(radioCaja)
                                .addGap(36, 36, 36)
                                .addComponent(radioSobre)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_solicitarPedido_, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recoleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCaja)
                    .addComponent(radioSobre))
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decrp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_solicitarPedido_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_solicitarPedido_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitarPedido_ActionPerformed
        // TODO add your handling code here:
 try {
        PedidoDTO pedido = new PedidoDTO();
        
        pedido.direccionOrigen = recoleccion.getText();
        pedido.direccionDestino = entrega.getText();
        pedido.idEmprendedor="EMP-001";
        pedido.descripcionPaquete = decrp.getText();
        pedido.pesoAproximado = Double.parseDouble(peso.getText());
        if(radioCaja.isSelected()) {
            pedido.tipoPaquete = "Caja";
        } else if (radioSobre.isSelected()) {
            pedido.tipoPaquete = "Sobre";
        }
        
        controlador.publicarPedido(pedido);
        PanelRepartidor panel = new pantallasvistarepartidor.PanelRepartidor(controlador);
        panel.setVisible(true);
        this.setVisible(false);
        
        } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El peso debe ser un número válido.");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btn_solicitarPedido_ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.guis.BotonNegro btn_solicitarPedido_;
    private javax.swing.JTextField decrp;
    private javax.swing.JTextField entrega;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField peso;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JRadioButton radioCaja;
    private javax.swing.JRadioButton radioSobre;
    private javax.swing.JTextField recoleccion;
    private javax.swing.JLabel tituloMotoAmigo;
    // End of variables declaration//GEN-END:variables
}
