package pantallasvistaemprendedor;

import com.mycompany.motoamigocontrol.ControladorPrincipal;
import util.Icon;

/**
 *
 * @author xiomi
 */
public class PanelEmprendedor extends javax.swing.JFrame {

    private ControladorPrincipal controlador;

    /**
     * Creates new form PanelEmprendedorGUI
     */
    public PanelEmprendedor(ControladorPrincipal controlador) {
        initComponents();
        this.controlador = controlador;
        this.setLocationRelativeTo(null);
        btn_nuevoEnvio.setIcon(Icon.cargarIcono("/imagenes/box.png", 15, 15));
        labelHomeIcon.setIcon(Icon.cargarIcono("/imagenes/home.png", 20, 20));
        labelHistorialIcon.setIcon(Icon.cargarIcono("/imagenes/pedidos.png", 20, 20));
        labelPerfilIcon.setIcon(Icon.cargarIcono("/imagenes/perfil.png", 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        tituloMotoAmigo = new javax.swing.JLabel();
        principalContainer = new javax.swing.JPanel();
        saludoEmprendedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_nuevoEnvio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelEnviosActivos = new javax.swing.JPanel();
        labelHomeIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelHistorialIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelPerfilIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashobard Emprendedor");

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 80));

        tituloMotoAmigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloMotoAmigo.setForeground(new java.awt.Color(251, 86, 0));
        tituloMotoAmigo.setText("MotoAmigo");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloMotoAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloMotoAmigo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        principalContainer.setBackground(new java.awt.Color(248, 250, 250));

        saludoEmprendedor.setBackground(new java.awt.Color(251, 86, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("!Hola Emprendedor!");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Que enviaremos hoy?");

        btn_nuevoEnvio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_nuevoEnvio.setForeground(new java.awt.Color(252, 9, 0));
        btn_nuevoEnvio.setText("Nuevo Envio");
        btn_nuevoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saludoEmprendedorLayout = new javax.swing.GroupLayout(saludoEmprendedor);
        saludoEmprendedor.setLayout(saludoEmprendedorLayout);
        saludoEmprendedorLayout.setHorizontalGroup(
            saludoEmprendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saludoEmprendedorLayout.createSequentialGroup()
                .addGroup(saludoEmprendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saludoEmprendedorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(saludoEmprendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(saludoEmprendedorLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btn_nuevoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        saludoEmprendedorLayout.setVerticalGroup(
            saludoEmprendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saludoEmprendedorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btn_nuevoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Envios Activos");

        jScrollPane1.setBackground(new java.awt.Color(248, 250, 252));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout panelEnviosActivosLayout = new javax.swing.GroupLayout(panelEnviosActivos);
        panelEnviosActivos.setLayout(panelEnviosActivosLayout);
        panelEnviosActivosLayout.setHorizontalGroup(
            panelEnviosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        panelEnviosActivosLayout.setVerticalGroup(
            panelEnviosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelEnviosActivos);

        labelHomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHomeIcon.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicio");

        labelHistorialIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHistorialIcon.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pedidos");

        labelPerfilIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPerfilIcon.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Perfil");

        javax.swing.GroupLayout principalContainerLayout = new javax.swing.GroupLayout(principalContainer);
        principalContainer.setLayout(principalContainerLayout);
        principalContainerLayout.setHorizontalGroup(
            principalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalContainerLayout.createSequentialGroup()
                .addGroup(principalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalContainerLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(saludoEmprendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(principalContainerLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(principalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(principalContainerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(principalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(principalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHistorialIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(principalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPerfilIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        principalContainerLayout.setVerticalGroup(
            principalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(saludoEmprendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(principalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalContainerLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                        .addGroup(principalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(principalContainerLayout.createSequentialGroup()
                                .addComponent(labelHomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addGroup(principalContainerLayout.createSequentialGroup()
                                .addComponent(labelHistorialIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))))
                    .addGroup(principalContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelPerfilIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoEnvioActionPerformed
        // TODO add your handling code here:

        PanelSolicitarEntrega panelSolicitar = new PanelSolicitarEntrega(this.controlador);
        panelSolicitar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_nuevoEnvioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nuevoEnvio;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHistorialIcon;
    private javax.swing.JLabel labelHomeIcon;
    private javax.swing.JLabel labelPerfilIcon;
    private javax.swing.JPanel panelEnviosActivos;
    private javax.swing.JPanel principalContainer;
    private javax.swing.JPanel saludoEmprendedor;
    private javax.swing.JLabel tituloMotoAmigo;
    // End of variables declaration//GEN-END:variables
}
