/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallasvistarepartidor;

import controlador.ControladorPrincipal;

/**
 *
 * @author Dell
 */
public class PantallaRecoleccion extends javax.swing.JFrame {
    
    
    private ControladorPrincipal controlador;
    private String idPedido;

    /**
     * Creates new form Panelrecoleccion
     */
    public PantallaRecoleccion(ControladorPrincipal controlador, String idPedido) {
        initComponents();
        this.controlador = controlador;
        this.idPedido = idPedido;
        this.setLocationRelativeTo(null);
        cargarDatosPedido();
    }
    
    private void cargarDatosPedido() {
    new Thread(() -> {
        try {
            com.mycompany.motoamigodto.pedido.PedidoDTO pedido =
                controlador.obtenerPedidoPorId(idPedido);

            if (pedido != null) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    labelDestino.setText(pedido.direccionOrigen); 
                    labelTiempo.setText(pedido.tiempoEstimadoMinutos + " minutos");
                });

                double[] coords = util.MapBoxService.geocodificar(pedido.direccionOrigen);
                java.awt.image.BufferedImage imagen =
                    util.MapBoxService.obtenerMapaEstatico(coords[0], coords[1], 350, 345);

                javax.swing.SwingUtilities.invokeLater(() -> {
                    javax.swing.JLabel labelMapa = new javax.swing.JLabel(
                        new javax.swing.ImageIcon(imagen)
                    );
                    panelMapaNavegacion.setLayout(new java.awt.BorderLayout());
                    panelMapaNavegacion.add(labelMapa, java.awt.BorderLayout.CENTER);
                    panelMapaNavegacion.revalidate();
                    panelMapaNavegacion.repaint();
                });
            }
        } catch (Exception e) {
            System.out.println("Error cargando mapa recolección: " + e.getMessage());
        }
    }).start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMapaNavegacion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        labelTiempo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        tituloMotoAmigo = new javax.swing.JLabel();
        footerPanel1 = new javax.swing.JPanel();
        labelHomeIcon1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelHistorialIcon1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelPerfilIcon1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_cancelarEntrega = new javax.swing.JButton();
        btn_pedidoRecolectado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelMapaNavegacionLayout = new javax.swing.GroupLayout(panelMapaNavegacion);
        panelMapaNavegacion.setLayout(panelMapaNavegacionLayout);
        panelMapaNavegacionLayout.setHorizontalGroup(
            panelMapaNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelMapaNavegacionLayout.setVerticalGroup(
            panelMapaNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("DESTINO");

        labelDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDestino.setText("Emprendedor");

        labelTiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTiempo.setText("15 minutos");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("TIEMPO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 80));

        tituloMotoAmigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloMotoAmigo.setForeground(new java.awt.Color(251, 86, 0));
        tituloMotoAmigo.setText("MotoAmigo");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloMotoAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloMotoAmigo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        footerPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelHomeIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHomeIcon1.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Inicio");

        labelHistorialIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHistorialIcon1.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pedidos");

        labelPerfilIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPerfilIcon1.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Perfil");

        javax.swing.GroupLayout footerPanel1Layout = new javax.swing.GroupLayout(footerPanel1);
        footerPanel1.setLayout(footerPanel1Layout);
        footerPanel1Layout.setHorizontalGroup(
            footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPerfilIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(footerPanel1Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelHomeIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(78, 78, 78)
                    .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelHistorialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(56, 56, 56)))
        );
        footerPanel1Layout.setVerticalGroup(
            footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelPerfilIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(footerPanel1Layout.createSequentialGroup()
                    .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(footerPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(footerPanel1Layout.createSequentialGroup()
                                    .addComponent(labelHomeIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel7))
                                .addGroup(footerPanel1Layout.createSequentialGroup()
                                    .addComponent(labelHistorialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel8))))
                        .addGroup(footerPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel9)))
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        btn_cancelarEntrega.setBackground(new java.awt.Color(0, 0, 0));
        btn_cancelarEntrega.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cancelarEntrega.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelarEntrega.setText("Cancelar");
        btn_cancelarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarEntregaActionPerformed(evt);
            }
        });

        btn_pedidoRecolectado.setBackground(new java.awt.Color(0, 201, 80));
        btn_pedidoRecolectado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_pedidoRecolectado.setForeground(new java.awt.Color(255, 255, 255));
        btn_pedidoRecolectado.setText("Pedido Recolectado");
        btn_pedidoRecolectado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedidoRecolectadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cancelarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pedidoRecolectado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelMapaNavegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelMapaNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancelarEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_pedidoRecolectado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(footerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarEntregaActionPerformed

    private void btn_pedidoRecolectadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedidoRecolectadoActionPerformed
        try {
            // 1. Cambiamos el estado a REPARTO en la BD
            controlador.confirmarRecoleccionPedido(this.idPedido);
            
            // 2. Pasamos a la pantalla de entregando
            PantallaEntregandoPedido entregando = new PantallaEntregandoPedido(this.controlador, this.idPedido);
            entregando.setVisible(true);
            this.dispose();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_pedidoRecolectadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarEntrega;
    private javax.swing.JButton btn_pedidoRecolectado;
    private javax.swing.JPanel footerPanel1;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelHistorialIcon1;
    private javax.swing.JLabel labelHomeIcon1;
    private javax.swing.JLabel labelPerfilIcon1;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JPanel panelMapaNavegacion;
    private javax.swing.JLabel tituloMotoAmigo;
    // End of variables declaration//GEN-END:variables
}
