/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallasvistarepartidor;

import controlador.ControladorPrincipal;
import util.MapBoxService;

/**
 *
 * @author xiomi
 */
public class PantallaEntregandoPedido extends javax.swing.JFrame {

    private ControladorPrincipal controlador;
    private String idPedido;

    /**
     * Creates new form PantallaNavegacion
     */
    public PantallaEntregandoPedido(ControladorPrincipal controlador, String idPedido) {
        initComponents();
        this.controlador = controlador;
        this.idPedido = idPedido;
        

        cargarDatosPedido();

    }

    private void cargarDatosPedido() {

        new Thread(() -> {
        try {
            com.mycompany.motoamigodto.pedido.PedidoDTO pedido =
                controlador.obtenerPedidoPorId(idPedido);

            if (pedido != null) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    labelDestino.setText(pedido.direccionDestino);
                    labelTiempo.setText(pedido.tiempoEstimadoMinutos + " minutos");
                });

                double[] destino = MapBoxService.geocodificar(pedido.direccionDestino);
                
                int ancho = 350;
                int alto  = 345;
                java.awt.image.BufferedImage imagen = 
                    MapBoxService.obtenerMapaEstatico(destino[0], destino[1], ancho, alto);

                javax.swing.SwingUtilities.invokeLater(() -> {
                    javax.swing.JLabel labelMapa = new javax.swing.JLabel(
                        new javax.swing.ImageIcon(imagen)
                    );
                    panelMapaNavegacion.setLayout(new java.awt.BorderLayout());
                    panelMapaNavegacion.add(labelMapa, java.awt.BorderLayout.CENTER);
                    panelMapaNavegacion.revalidate();
                    panelMapaNavegacion.repaint();
                });
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPadre = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        tituloMotoAmigo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        labelTiempo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_registrarIncidente = new javax.swing.JButton();
        btn_marcarEntregado = new javax.swing.JButton();
        panelMapaNavegacion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("En Recolección");

        panelPadre.setBackground(new java.awt.Color(248, 250, 252));

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 80));

        tituloMotoAmigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloMotoAmigo.setForeground(new java.awt.Color(251, 86, 0));
        tituloMotoAmigo.setText("MotoAmigo");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloMotoAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloMotoAmigo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("DESTINO");

        labelDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDestino.setText("Guerrero 287");

        labelTiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTiempo.setText("15 minutos");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("TIEMPO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        btn_registrarIncidente.setBackground(new java.awt.Color(0, 0, 0));
        btn_registrarIncidente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_registrarIncidente.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarIncidente.setText("Reportar Incidente");

        btn_marcarEntregado.setBackground(new java.awt.Color(0, 201, 80));
        btn_marcarEntregado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_marcarEntregado.setForeground(new java.awt.Color(255, 255, 255));
        btn_marcarEntregado.setText("Marcar como entregado");
        btn_marcarEntregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_marcarEntregadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMapaNavegacionLayout = new javax.swing.GroupLayout(panelMapaNavegacion);
        panelMapaNavegacion.setLayout(panelMapaNavegacionLayout);
        panelMapaNavegacionLayout.setHorizontalGroup(
            panelMapaNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        panelMapaNavegacionLayout.setVerticalGroup(
            panelMapaNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPadreLayout = new javax.swing.GroupLayout(panelPadre);
        panelPadre.setLayout(panelPadreLayout);
        panelPadreLayout.setHorizontalGroup(
            panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPadreLayout.createSequentialGroup()
                .addGroup(panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPadreLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPadreLayout.createSequentialGroup()
                                .addComponent(btn_registrarIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_marcarEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelPadreLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelMapaNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPadreLayout.setVerticalGroup(
            panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPadreLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelMapaNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_registrarIncidente, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_marcarEntregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_marcarEntregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_marcarEntregadoActionPerformed
        try {
            //  Cambiamos el estado a ENTREGADO
            controlador.marcarPedidoComoEntregado(this.idPedido);

            javax.swing.JOptionPane.showMessageDialog(this, "¡Excelente trabajo! Has completado la entrega.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            //  Regresamos al menú principal del repartidor
            PanelRepartidor inicio = new PanelRepartidor(this.controlador);
            inicio.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_marcarEntregadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_marcarEntregado;
    private javax.swing.JButton btn_registrarIncidente;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JPanel panelMapaNavegacion;
    private javax.swing.JPanel panelPadre;
    private javax.swing.JLabel tituloMotoAmigo;
    // End of variables declaration//GEN-END:variables
}
